### ISSUE TITLE
Need Help!

### ISSUE THREAD

**Issue by victorydst3** [KyutoxGlory/loq18#1]
Can you add me code owner to this project? 
I'm from Tea community

**Comment by KyutoxGlory** [comment]
For add contributor?


Pada Min, 31 Mar 2024 pukul 11.06 Huỳnh Lê Bá Vinh ***@***.***>
menulis:

**Comment by VinhHuynh93** [comment]
Yes sir

**Comment by KyutoxGlory** [comment]
It doesn't seem possible, I've already committed to the project, maybe if I
rebuild it I'll let you know

Pada Min, 31 Mar 2024 pukul 11.11 victorydst3 ***@***.***>
menulis:

**Comment by victorydst3** [comment]
Thanks, and can you please add my tea code to this project?
My code defined here.
https://github.com/victorydst3/tea-future/blob/main/tea.yaml#L5
